### ISSUE TITLE
Sagesoul/Nailsage's Tenacity removes Attuned from Sly

### ISSUE THREAD

**Issue by Araraura** [Xhuis/Exaltation#2]
If you have the Sagesoul/Nailsage's Tenacity charm equipped after you defeat Sly at Attuned difficulty, it will remove the Attuned icon from the hall of gods.

**Comment by Xhuis** [comment]
This was the main way to allow swapping between them; unfortunately, I'm not sure of a workaround. I could likely find one, but I no longer work on the mod.
